const assert = require('node:assert/strict')
const path = require('node:path')
const { test } = require('node:test')
const { launch, route, settled } = require('./helpers/motion-fixture.cjs')
const rendererPath = process.env.LX_TEST_USE_DEV_SERVER ? undefined : path.resolve('dist/index.html')

const rpc = (page, method, ...args) => page.evaluate(({ method, args }) => require('electron').ipcRenderer.invoke('winMain_library_action', { method, args }), { method, args })
const songs = page => page.evaluate(() => require('electron').ipcRenderer.invoke('player_list_music_get', 'default'))

test('playlist tags move to the context menu and listening history replaces the trial list', { timeout: 120000 }, async() => {
  let f = await launch({ rendererPath })
  const profilePath = f.output
  const first = { id: 'wy_first', name: '历史歌曲一', singer: '测试歌手', source: 'wy', interval: '03:00', meta: { songId: 'first' } }
  const second = { ...first, id: 'wy_second', name: '历史歌曲二', meta: { songId: 'second' } }
  try {
    f.page.setDefaultTimeout(12000)
    await f.page.evaluate(async song => {
      await require('electron').ipcRenderer.invoke('player_list_data_overwire', {
        defaultList: [song], loveList: [], tempList: [],
        userList: [{ id: 'one', name: '测试歌单', locationUpdateTime: null, list: [song] }],
      })
    }, first)
    await route(f.page, '/list?id=one')
    await settled(f.page)
    assert.equal(await f.page.getByRole('button', { name: '曲库管理' }).count(), 0)
    assert.equal(await f.page.locator('#my-list .default-list[aria-label="听歌历史"]').count(), 1)
    assert.equal(await f.page.locator('#my-list .default-list[aria-label="试听列表"]').count(), 0)

    await f.page.locator('#my-list .user-list[data-id="one"]').click({ button: 'right' })
    await f.page.getByRole('tab', { name: '编辑标签' }).click()
    const modal = f.page.locator('[data-playlist-tags-modal]')
    const tagInput = modal.getByLabel('标签')
    await tagInput.fill('学习，收藏, 学习')
    const inputBox = await tagInput.boundingBox()
    const panelBox = await modal.boundingBox()
    assert(inputBox && panelBox)
    const outside = { x: panelBox.x - 24, y: inputBox.y + inputBox.height / 2 }
    assert(outside.x > 0)
    await f.page.mouse.move(inputBox.x + inputBox.width * .7, outside.y)
    await f.page.mouse.down()
    await f.page.mouse.move(outside.x, outside.y, { steps: 8 })
    await f.page.mouse.up()
    await f.page.waitForTimeout(500)
    assert.equal(await modal.isVisible(), true, 'releasing a text selection over the backdrop must keep the editor open')
    assert.equal(await tagInput.inputValue(), '学习，收藏, 学习')
    await f.page.mouse.click(outside.x, outside.y)
    await modal.waitFor({ state: 'hidden' })
    await f.page.locator('#my-list .user-list[data-id="one"]').click({ button: 'right' })
    await f.page.getByRole('tab', { name: '编辑标签' }).click()
    await modal.getByLabel('标签').fill('学习，收藏, 学习')
    await modal.getByRole('button', { name: '确定' }).click()
    await f.page.waitForFunction(() => document.querySelector('#my-list .user-list[data-id="one"]')?.textContent.includes('学习 / 收藏'))
    assert.deepEqual((await rpc(f.page, 'getLibraryPreferences')).lists.one.tags, ['学习', '收藏'])

    await f.app.evaluate(async(_electron, tracks) => {
      await global.lx.worker.dbService.recordListening(tracks[0], new Date('2026-09-01T12:00:00').getTime())
      await global.lx.worker.dbService.recordListening(tracks[0], new Date('2026-09-01T12:01:00').getTime())
      await global.lx.worker.dbService.recordListening(tracks[1], new Date('2026-09-02T12:00:00').getTime())
    }, [first, second])
    await f.page.locator('#my-list .default-list[aria-label="听歌历史"]').click()
    await f.page.locator('[data-listening-history]').waitFor()
    await f.page.locator('#my-list .user-list[data-id="one"]').click({ button: 'right' })
    await f.page.getByRole('tab', { name: '编辑标签' }).click()
    await f.page.locator('[data-playlist-tags-modal]').getByRole('button', { name: '取消' }).click()
    await f.page.locator('[data-playlist-tags-modal]').waitFor({ state: 'hidden' })
    const history = f.page.locator('[data-listening-history]')
    const rows = history.locator('[data-history-id]')
    await rows.first().waitFor()
    assert.equal(await history.locator('form').count(), 0)
    assert.equal(await history.getByRole('button', { name: '查询' }).count(), 0)
    assert.equal(await history.getByRole('button', { name: '清空历史' }).count(), 1)
    assert.equal(await rows.count(), 3)
    assert.deepEqual((await history.locator('[data-music-column]').allTextContents()).map(text => text.trim()), ['#', '封', '歌曲名', '艺术家', '专辑名', '时长', '收听时间'])
    assert.match(await rows.first().locator('[data-music-cell="name"]').innerText(), /历史歌曲二/)
    assert.equal(await rows.first().locator('[data-music-cell="time"]').innerText(), '03:00')
    const beforeRemoval = await rpc(f.page, 'getListeningHistory')
    assert.equal(await rows.first().locator('[data-music-cell="action"] time').getAttribute('datetime'), new Date(beforeRemoval.rows[0].time).toISOString())
    await rows.nth(1).click({ button: 'right' })
    await f.page.getByRole('tab', { name: '添加到...' }).waitFor()
    await f.page.getByRole('tab', { name: '移除', exact: true }).click()
    await f.page.waitForFunction(() => document.querySelectorAll('[data-listening-history] [data-history-id]').length === 2)
    const afterRemoval = await rpc(f.page, 'getListeningHistory')
    assert.equal(afterRemoval.stats.plays, 2)
    assert.equal(afterRemoval.rows.some(row => row.id === beforeRemoval.rows[1].id), false)
    assert.equal(afterRemoval.rows.some(row => row.id === beforeRemoval.rows[2].id), true, 'another play of the same song must remain')
    await f.page.screenshot({ path: path.join(profilePath, 'listening-history.png') })
    await f.page.evaluate(() => window.i18n.setLanguage('en-us'))
    await f.page.getByRole('heading', { name: 'Listening history' }).waitFor()
    assert.equal(await history.locator('[data-music-column="action"]').innerText(), 'Listened at')
    assert.equal(await f.page.locator('#my-list .default-list[aria-label="Listening history"]').count(), 1)
    await f.page.evaluate(() => window.i18n.setLanguage('zh-cn'))
    assert.equal((await songs(f.page)).length, 1, 'former trial-list data should not be erased')
    assert.deepEqual(f.errors, [])

    await f.app.close()
    f = await launch({ profilePath, rendererPath })
    assert.deepEqual((await rpc(f.page, 'getLibraryPreferences')).lists.one.tags, ['学习', '收藏'])
    assert.equal((await rpc(f.page, 'getListeningHistory')).stats.plays, 2)
    await route(f.page, '/list?id=history')
    await f.page.locator('[data-listening-history]').getByRole('button', { name: '清空历史' }).click()
    await f.page.getByRole('button', { name: '清空历史' }).last().click()
    await f.page.waitForFunction(() => document.querySelector('[data-listening-history]')?.textContent.includes('共播放 0 次'))
    assert.equal((await rpc(f.page, 'getListeningHistory')).stats.plays, 0)
    assert.deepEqual(f.errors, [])
    console.log('Listening history UI evidence: ' + profilePath)
  } finally { await f.app.close() }
})
