const assert = require('node:assert/strict')
const path = require('node:path')
const http = require('node:http')
const { test } = require('node:test')
const { launch, route, settled } = require('./helpers/motion-fixture.cjs')
const { createDAV, playlists, song } = require('./helpers/webdav-fixture.cjs')
const invoke = (page, channel, params) => page.evaluate(({ channel, params }) => require('electron').ipcRenderer.invoke(channel, params), { channel, params })

test('F06/F11: sync status, playlist selection and visible conflicts', { timeout: 100000 }, async t => {
  const dav = await createDAV()
  const platform = http.createServer((req, res) => res.writeHead(200, { 'Content-Type': 'application/json' }).end(JSON.stringify({ code: '000000', data: { myCreatedMusicLists: { createdMusicLists: [{ musicListId: 'one', title: '平台歌单一' }, { musicListId: 'two', title: '平台歌单二' }] } } })))
  await new Promise(resolve => platform.listen(0, '127.0.0.1', resolve))
  let fixture
  t.after(async() => { if (fixture) await fixture.app.close(); await dav.close(); platform.closeAllConnections(); await new Promise(resolve => platform.close(resolve)) })
  fixture = await launch({ initializeMotion: false, rendererPath: path.resolve('dist/index.html') })
  const { app, page } = fixture
  await app.evaluate(async(_, config) => {
    await global.lx.event_app.update_config({ ...Object.fromEntries(Object.entries(config).map(([key, value]) => ['sync.webdav.' + key, value])), 'sync.webdav.enable': true, 'player.volume': 0, 'common.langId': 'zh-cn' })
  }, dav.config)
  await route(page, '/setting?name=SettingSync'); await settled(page)
  assert.equal(await page.getByRole('heading', { name: '平台歌单同步范围' }).count(), 0)
  assert.equal(await page.getByRole('region', { name: 'WebDAV 音频目录' }).count(), 0)
  await t.test('persist a selected/ignored playlist range and retain hidden selections', async() => {
    await page.evaluate(port => {
      const https = require('https'), http = require('http'), request = https.request
      https.request = function(options, callback) {
        if ((options.hostname ?? options.host) === 'c.musicapp.migu.cn') return http.request({ ...options, protocol: 'http:', hostname: '127.0.0.1', host: '127.0.0.1', port, agent: undefined }, callback)
        return request.apply(this, arguments)
      }
      window.lxData.appSetting['cookie.mg'] = 'mg_auth_uid=7; mg_auth_pacmtoken=fixture-session'
    }, platform.address().port)
    await route(page, '/list?id=history'); await settled(page)
    await page.getByRole('button', { name: '列表更新管理', exact: true }).click()
    await page.getByRole('button', { name: '平台同步范围', exact: true }).click()
    await page.getByRole('combobox', { name: '选择平台' }).click()
    await page.getByText('咪咕音乐', { exact: true }).last().click()
    await page.getByRole('button', { name: '读取平台歌单' }).click()
    await page.locator('label[for="sync_selection_mg_one"]').click()
    await page.getByPlaceholder('搜索歌单', { exact: true }).fill('二')
    await page.getByRole('button', { name: '选中筛选结果' }).click()
    await page.getByRole('combobox', { name: '同步范围' }).click()
    await page.getByText('忽略选中的歌单', { exact: true }).last().click()
    await page.getByRole('button', { name: '保存同步范围' }).click()
    await page.getByText('同步范围已保存', { exact: true }).waitFor()
    await page.locator('.selection-list').waitFor({ state: 'detached' })
    await page.screenshot({ path: path.resolve('logs/list-update-scope.png') })
    assert.deepEqual(await app.evaluate(() => JSON.parse(global.lx.appSetting['sync.platform.selection']).mg), { mode: 'exclude', ids: ['one', 'two'] })
    await route(page, '/setting?name=SettingSync'); await settled(page)
  })
  await t.test('conflict preview, failed-only filtering and retry retain the last successful time', async() => {
    await app.evaluate(async(_, lists) => global.lx.event_list.list_data_overwrite(lists), playlists('before'))
    await page.getByRole('button', { name: '立即同步', exact: true }).click()
    await page.getByRole('status').filter({ hasText: '上传 1 项' }).waitFor()
    const baseline = await invoke(page, 'winMain_webdav_last_result')
    await app.evaluate(async(_, lists) => global.lx.event_list.list_data_overwrite(lists), playlists('local-change'))
    const remote = playlists('remote-change')
    remote.userList.push({ id: 'new-list', name: '云端新增歌单', locationUpdateTime: null, list: [song('new')] })
    dav.seed({ playlists: remote })
    await page.getByRole('button', { name: '立即同步', exact: true }).click()
    await page.getByText(/远端相对本地的差异/).waitFor()
    await page.getByRole('cell', { name: '云端新增歌单', exact: true }).first().waitFor()
    await page.evaluate(() => window.i18n.setLanguage('en-us'))
    await page.getByText(/Remote changes relative to local data/).waitFor()
    await page.getByRole('columnheader', { name: 'Change', exact: true }).waitFor()
    await page.getByRole('cell', { name: 'Added', exact: true }).first().waitFor()
    assert.equal(await page.getByRole('button', { name: 'View sync status', exact: true }).count(), 1)
    await page.evaluate(() => window.i18n.setLanguage('zh-tw'))
    await page.getByText(/遠端相對本機的差異/).waitFor()
    await page.getByRole('columnheader', { name: '變化', exact: true }).waitFor()
    assert.equal(await page.getByRole('button', { name: '查看同步狀態', exact: true }).count(), 1)
    await page.evaluate(() => window.i18n.setLanguage('zh-cn'))
    const statusButton = page.getByRole('button', { name: '查看同步状态', exact: true })
    const statusDialog = page.getByRole('dialog', { name: '同步状态', exact: true })
    assert.equal(await statusDialog.count(), 0)
    await statusButton.click()
    await statusDialog.getByPlaceholder('搜索平台或歌单').fill('WebDAV')
    await statusDialog.locator('label[for="sync_errors_only"]').click()
    const row = statusDialog.locator('li').filter({ has: page.locator('strong', { hasText: /^WebDAV$/ }) })
    await row.getByText(/WEBDAV_CONFLICT/).waitFor()
    assert((await row.textContent()).includes('最近成功'))
    assert.equal((await invoke(page, 'winMain_webdav_last_result')).lastSuccess, baseline.lastSuccess)
    dav.seed({ playlists: playlists('local-change') })
    await row.getByRole('button', { name: '重试', exact: true }).click()
    await row.waitFor({ state: 'detached' })
    await statusDialog.locator('label[for="sync_errors_only"]').click()
    await statusDialog.locator('xpath=..').locator('header button').click()
    await statusDialog.waitFor({ state: 'hidden' })
    await statusButton.click()
    await statusDialog.getByText('WebDAV', { exact: true }).first().waitFor()
    await page.waitForTimeout(400)
    await page.screenshot({ path: path.resolve('logs/sync-features.png') })
  })
  assert.deepEqual(fixture.errors, [])
  assert.deepEqual(dav.errors, [])
  const profilePath = fixture.output
  await app.close(); fixture = null
  fixture = await launch({ initializeMotion: false, rendererPath: path.resolve('dist/index.html'), profilePath })
  await route(fixture.page, '/setting?name=SettingSync'); await settled(fixture.page)
  assert.equal(await fixture.page.getByRole('heading', { name: '平台歌单同步范围' }).count(), 0)
  await route(fixture.page, '/list?id=history'); await settled(fixture.page)
  await fixture.page.getByRole('button', { name: '列表更新管理', exact: true }).click()
  await fixture.page.getByRole('button', { name: '平台同步范围', exact: true }).click()
  await fixture.page.getByRole('combobox', { name: '选择平台' }).click()
  await fixture.page.getByText('咪咕音乐', { exact: true }).last().click()
  assert.equal(await fixture.page.getByRole('combobox', { name: '同步范围' }).innerText(), '忽略选中的歌单')
  assert.deepEqual(await fixture.app.evaluate(() => JSON.parse(global.lx.appSetting['sync.platform.selection']).mg.ids), ['one', 'two'])
  await route(fixture.page, '/setting?name=SettingSync'); await settled(fixture.page)
  const restoredStatus = await fixture.page.evaluate(() => JSON.parse(localStorage.getItem('lx-sync-status-v1')).webdav)
  assert.equal(restoredStatus.state, 'success'); assert(restoredStatus.lastSuccess > 0)
  await fixture.page.getByLabel('密码 / 应用专用密码').fill('invalid')
  await fixture.page.getByRole('button', { name: '测试连接', exact: true }).click()
  await fixture.page.getByRole('status').filter({ hasText: 'HTTP_401' }).waitFor()
  assert((await fixture.page.getByRole('status').filter({ hasText: 'HTTP_401' }).textContent()).includes('原因'))
  assert.deepEqual(fixture.errors, [])
})
