const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { test } = require('node:test')
const { auditPackages } = require('../build-config/win7/audit.cjs')

test('nested anonymous module scopes retain their owning package engine checks', t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'lx-package-audit-'))
  t.after(() => fs.rmSync(root, { recursive: true, force: true }))
  const pkg = path.join(root, 'node_modules', 'fixture')
  const scope = path.join(pkg, 'dist')
  fs.mkdirSync(scope, { recursive: true })
  fs.writeFileSync(path.join(scope, 'package.json'), JSON.stringify({ type: 'module' }))
  const manifest = path.join(pkg, 'package.json')
  fs.writeFileSync(manifest, JSON.stringify({ name: 'fixture', version: '1.0.0', engines: { node: '>=14' } }))
  assert.deepEqual(auditPackages([], [path.join(scope, 'index.js')]), [{ name: 'fixture', version: '1.0.0', node: '>=14' }])
  fs.writeFileSync(manifest, JSON.stringify({ name: 'fixture', version: '1.0.0', engines: { node: '>=18' } }))
  assert.throws(() => auditPackages([], [path.join(scope, 'index.js')]), /Dependencies incompatible with Node 16.*fixture/)
})
