import { computed } from 'vue'
import { appSetting } from '@renderer/store/setting'

const copy = {
  'zh-cn': {
    intro: '编辑音频文件内的标签，保存后可在文件属性和其他播放器中查看。原有封面、歌词和音频内容会保留。',
    choose: '选择音频文件',
    refresh: '刷新下载列表',
    downloads: '已完成的下载',
    search: '搜索文件名或艺术家',
    loading: '正在读取下载列表…',
    downloadError: '下载列表读取失败，请刷新重试，也可以直接选择音频文件。',
    noDownloads: '暂无已完成的 MP3、FLAC 下载。可点击上方按钮选择本地文件。',
    noMatch: '没有匹配的文件',
    more: '显示更多',
    start: '选择要编辑的音频文件',
    startHint: '从左侧选择已完成的下载、在下载页面右键修改音频标签，或打开本地 MP3、FLAC 文件。',
    unsaved: '未保存',
    saved: '标签已保存到音频文件。',
    working: '正在处理…',
    save: '保存标签',
    reset: '还原修改',
    shortcut: 'Ctrl / ⌘ + S 保存',
    discard: '当前标签有未保存的修改，是否放弃修改并打开另一个文件？',
    discardConfirm: '放弃并打开',
    cancel: '继续编辑',
    fields: { title: '标题', subtitle: '副标题', artist: '艺术家', albumArtist: '专辑艺术家', album: '专辑', year: '年份 / 日期', track: '曲目序号', disc: '光盘序号', genre: '流派', composer: '作曲者', publisher: '发行者', encodedBy: '编码人员', copyright: '版权', comment: '备注' },
    errors: {
      ENOENT: '文件不存在或已移动，请重新选择文件。',
      ENOTDIR: '文件所在的目录不存在或已移动，请重新选择文件。',
      TASK_MISSING: '下载记录已删除，请刷新下载列表，或直接选择音频文件。',
      DOWNLOAD_INCOMPLETE: '歌曲尚未下载完成，或正在重新下载，请等待下载完成后再编辑标签。',
      INVALID_PATH: '下载记录中的文件路径无效，请直接选择音频文件。',
      AMBIGUOUS_FILE: '下载目录中找到多个同名文件，请通过“选择音频文件”确认要编辑的文件。',
      EACCES: '没有文件写入权限，请检查文件是否为只读。',
      EPERM: '文件无法修改，请检查写入权限，并关闭其他正在使用此文件的程序。',
      EBUSY: '文件正在被使用，请关闭占用此文件的程序后重试。',
      ENOSPC: '磁盘空间不足，无法保存标签。',
      FILE_BUSY: '标签编辑器正在处理文件，请稍后重试。',
      FILE_CHANGED: '文件在打开后已被修改。请重新选择文件，读取最新标签后再保存。',
      UNSUPPORTED_FILE: '请选择 MP3 或 FLAC 音频文件。',
      UNSUPPORTED_TAG: '此 MP3 的标签格式暂不支持编辑，文件未修改。',
      INVALID_FILE: '无法读取此音频文件，文件可能损坏或格式与扩展名不一致。',
      INVALID_TAGS: '标签内容无效或过长，请检查后重试。',
      UNKNOWN: '无法读取或保存标签，请检查文件和写入权限后重试。',
    },
  },
  'en-us': {
    intro: 'Edit tags stored in audio files. Saved tags appear in file properties and other players. Existing artwork, lyrics and audio are preserved.',
    choose: 'Choose audio file',
    refresh: 'Refresh downloads',
    downloads: 'Completed downloads',
    search: 'Search filename or artist',
    loading: 'Loading downloads…',
    downloadError: 'Could not load downloads. Refresh or choose an audio file directly.',
    noDownloads: 'No completed MP3 or FLAC downloads. Choose a local file above.',
    noMatch: 'No matching files',
    more: 'Show more',
    start: 'Choose an audio file to edit',
    startHint: 'Select a completed download, right-click a song in Downloads to edit its tags, or open a local MP3 or FLAC file.',
    unsaved: 'Unsaved',
    saved: 'Tags saved to the audio file.',
    working: 'Working…',
    save: 'Save tags',
    reset: 'Reset changes',
    shortcut: 'Ctrl / ⌘ + S to save',
    discard: 'Discard unsaved tag changes and open another file?',
    discardConfirm: 'Discard and open',
    cancel: 'Keep editing',
    fields: { title: 'Title', subtitle: 'Subtitle', artist: 'Artist', albumArtist: 'Album artist', album: 'Album', year: 'Year / date', track: 'Track number', disc: 'Disc number', genre: 'Genre', composer: 'Composer', publisher: 'Publisher', encodedBy: 'Encoded by', copyright: 'Copyright', comment: 'Comment' },
    errors: {
      ENOENT: 'The file is missing or was moved. Choose it again.',
      ENOTDIR: 'The file directory is missing or was moved. Choose the file again.',
      TASK_MISSING: 'The download record was removed. Refresh downloads or choose the audio file directly.',
      DOWNLOAD_INCOMPLETE: 'The song has not finished downloading or is downloading again. Wait until it completes before editing tags.',
      INVALID_PATH: 'The download has an invalid file path. Choose the audio file directly.',
      AMBIGUOUS_FILE: 'Multiple files have the same name in the download directories. Use Choose audio file to select the correct one.',
      EACCES: 'Write access denied. Check whether the file is read-only.',
      EPERM: 'Cannot modify the file. Check permissions and close other programs using it.',
      EBUSY: 'The file is in use. Close other programs using it and try again.',
      ENOSPC: 'Not enough disk space to save tags.',
      FILE_BUSY: 'The tag editor is processing a file. Try again shortly.',
      FILE_CHANGED: 'The file changed after it was opened. Select it again to reload its tags before saving.',
      UNSUPPORTED_FILE: 'Choose an MP3 or FLAC audio file.',
      UNSUPPORTED_TAG: 'Editing this MP3 tag format is not supported. The file was not changed.',
      INVALID_FILE: 'Cannot read this audio file. It may be damaged or have the wrong extension.',
      INVALID_TAGS: 'Tags are invalid or too long. Check them and try again.',
      UNKNOWN: 'Could not read or save tags. Check the file and its write permissions.',
    },
  },
}
export const text = computed(() => copy[appSetting['common.langId']?.startsWith('zh') ? 'zh-cn' : 'en-us'])
export const fieldNames = Object.keys(copy['zh-cn'].fields)
